### ISSUE TITLE
IViewModelLocator not found on higher level hierarchies (WPF-ViewFirst)

### ISSUE THREAD

**Issue by dlaes** [tibel/Caliburn.Light#105]
On starting a WPF-Application with 3 nested views (Shell->ChildLevel1->ChildLevel2) an InvalidOperationException is thrown, if the child views are activated in ther parents `OnActivateAsync` method. Using the synchronous OnActivate of former versions of Caliburn.Light worked always as expected.

ShellView and ChildLevel1View:
`<ContentControl DataContext="{Binding ActiveItem, Mode=OneWay}" cal:View.Create="True" />`

The ViewModels:
```
public class ShellViewModel : Conductor<Screen>.Collection.OneActive{
    private ChildLevel1 _childLevel1;		// created by DI
	
    protected override async Task OnActivateAsync()
    {
        await ActivateItemAsync(_childLevel1);
    }
}

public class ChildLevel1 : Conductor<Screen>.Collection.OneActive
{
    private ChildLevel2 _childLevel2;		// created by DI
	
    protected override async Task OnActivateAsync()
    {
        await ActivateItemAsync(_childLevel2);
    }
}

public class ChildLevel2 : Screen
{
}
```
This constellation results in an exception on startup:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Could not find 'IViewModelLocator' in control hierarchy.
  Source=Caliburn.Light.WPF
  StackTrace:
at Caliburn.Light.WPF.View.CreateView(FrameworkElement parentElement, Object model, String context)
   at Caliburn.Light.WPF.View.OnDataContextChanged(Object sender, DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.RaiseDependencyPropertyChanged(EventPrivateKey key, DependencyPropertyChangedEventArgs args)
   at System.Windows.FrameworkElement.OnDataContextChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
...
at System.Windows.Window.Show()
   at Caliburn.Light.WPF.WindowManager.ShowWindow(Object viewModel, String context)
   at WpfApp2.App.OnStartup(StartupEventArgs e) 
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
```
Maybe Caliburn.Light tries to create the View of ChildLevel2 before the View of ChildLevel1?

**Comment by tibel** [comment]
fixed in 5.2.1
